# Travis Lint : https://lint.travis-ci.org
# Config secure
language: java
jdk:
  - oraclejdk8
install: 
  - mvn clean install
# La tâche de deploy est rajoutée à partir du template .travis.yml qui injecte les bons n° de versions